### ISSUE TITLE
Working yesterday, blank screen today

### ISSUE THREAD

**Issue by lacymorrow** [sircharleswatson/Electrometeor#33]
One of those days, wanted to see if you had any insight I may be overlooking.

Had Electroometeor running (first-try) yesterday **with my app** on OSX (running through localhost:3000 and Electron, _not_ built).

Re-cloned my project today and tried again, I'm getting a blank Electron window **with the demo/test app** (localhost still works). I've restarted, not sure where else to start.

**Comment by sjmcdowall** [comment]
Well this has been a known bug for a while (since day 1).  IMHO -- I think it's a latency issue where the app doesn't wait until all the piece components (namely the mongodb) are properly initialized and running -- thus launching the app too early and getting an empty window.  But -- that's just me. :)

**Comment by nagelflorian** [comment]
@lacymorrow I've just checked out Electrometeor for the first time and encountered the problem too. Like @sjmcdowall said it's likely due to the initialization of Meteor after the window appears. By simply pressing `cmd + r` (Mac) you can reload the window/WebView and your Meteor app should appear now.

**Comment by sircharleswatson** [comment]
Hey guys, so this issue didn't happen at all until after I accepted a pull request to update the versions. So, I'm not sure if upgrading again will fix it or not but I'd try that!

At the moment I don't really have time to work on Electrometeor unfortunately.

**Comment by lacymorrow** [comment]
@nagelflorian You're correct! that's the issue. Now to figure out a workaround.
